name: Build and deploy ASP app to Azure Web App - dotnet302

on:
  push:
    branches:
      - dotnet
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:Rebuild /p:_PackageTempDir="published"  # Make sure we're using the correct targets (Rebuild, not just Build)
      
      - name: List published files (debugging)
        run: dir published  # Added this to list contents of the published directory for debugging

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: 'published/**'  # Ensure the correct path to upload

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: './artifact'  # Specify the folder where the artifact is downloaded

      - name: List downloaded files (debugging)
        run: dir ./artifact  # List files to make sure they were downloaded

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_89A764F789ED49058D4FDAD54E60E356 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_61507E740BE447B08BA1207C02207552 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0DB71A8D06264F64B45F6A2CFD064726 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dotnet302'
          slot-name: 'Production'
          package: './artifact'  # Correct path to the downloaded artifact
